"""empty message

Revision ID: bf2e6c0dc365
Revises: 2c2c260d7956
Create Date: 2020-02-26 14:10:10.014404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf2e6c0dc365'
down_revision = '2c2c260d7956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customername', sa.String(length=64), nullable=True),
    sa.Column('customerno', sa.Integer(), nullable=True),
    sa.Column('customertype', sa.String(length=64), nullable=True),
    sa.Column('customerbalance', sa.Integer(), nullable=True),
    sa.Column('customermobile', sa.Integer(), nullable=True),
    sa.Column('customeraadhar', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customername'),
    sa.UniqueConstraint('customerno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
